### ISSUE TITLE
The git tag specified in the podspec does not correspond to the tag in the repo.

### ISSUE THREAD

**Issue by anthonymlagrange** [rahulnadella/FuzzySearch#3]
Hi - I've opened a pull request to have the git tag refered to in the podspec changed from "v1.1.0" to "1.1.0" so that it matches the actual git tag in the repo. As it is, `pod install` fails.

If you prefer, the git tag in the repo could instead be changed from `1.1.0` to `v1.1.0`. That would mean that no additional change is required to the podspec at https://github.com/CocoaPods/Specs/blob/master/Specs/FuzzySearch/1.1.0/FuzzySearch.podspec.json.

Thanks for the library!

**Comment by rahulnadella** [comment]
Anthony,

Thanks for fixing this. Supposed emailed me awhile ago but got busy with work.

Rahul
